services:
  vault_kms:
    image: hashicorp/vault:latest
    container_name: attt-kms-container
    ports:
      - "8200:8200"
    volumes:
      - ./vault_kms/config.hcl:/vault/config/config.hcl
      - ./vault_kms/data:/vault/file
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_CONFIG_DIR=/vault/config
    command: vault server -config=/vault/config/config.hcl
    restart: always

  postgres_db:
    image: postgres:15-alpine
    container_name: attt-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ekyc_admin
      - POSTGRES_PASSWORD=SuperStrongPass!No1
      - POSTGRES_DB=ekyc_matrix
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
