services:
  vault_kms:
    image: hashicorp/vault:latest
    container_name: attt-kms-container
    ports:
      - "8200:8200"
    volumes:
      - ./vault_kms/config.hcl:/vault/config/config.hcl
      - ./vault_kms/data:/vault/file
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_CONFIG_DIR=/vault/config
    command: vault server -config=/vault/config/config.hcl
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: attt-backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    env_file:
      - .env
    environment:
      - VAULT_URL=http://vault_kms:8200
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - vault_kms
    restart: always

